name = "revokeguard-frontend"

# مسیر خروجی Build پروژه (Cloudflare Pages از این استفاده می‌کند)
pages_build_output_dir = "dist"

# غیرفعال کردن Worker ها (چون پروژه فقط Frontend Pages است)
main = ""
compatibility_date = "2024-01-01"

# تنظیمات اضافی پیشنهادی
workers_dev = false
